pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: PyTest
        identifier: PyTest
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: PyTest
          project: default_project
          inputs:
            identifier: PyTest
            properties:
              ci:
                codebase:
                  build: <+input>
    - stage:
        name: BanditRepoScan
        identifier: BanditRepoScan
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: BanditScan
          project: default_project
          inputs:
            identifier: BanditScan
            properties:
              ci:
                codebase:
                  build: <+input>
            stages:
              - stage:
                  identifier: BanditRepoScan
                  type: SecurityTests
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: Bandit_1
                            type: Bandit
                            spec:
                              target:
                                type: repository
                                name: <+input>
                                variant: <+input>
        when:
          pipelineStatus: All
    - stage:
        name: BuildApproval
        identifier: BuildApproval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval
                  identifier: Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - Approval
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
        when:
          pipelineStatus: All
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |+
                      export sha=$(git rev-parse HEAD)

                    outputVariables:
                      - name: sha
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
        when:
          pipelineStatus: All
    - stage:
        name: "Build and push "
        identifier: Build_and_push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: demo
                    repo: carthmannh/week4demo
                    tags:
                      - <+pipeline.stages.Build.spec.execution.steps.Run_2.output.outputVariables.sha>
                    dockerfile: Dockerfile
        when:
          pipelineStatus: All
    - stage:
        name: CDStage
        identifier: CDStage
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: K8Deployment
          project: default_project
          inputSetReferences:
            - demonstest
        when:
          pipelineStatus: All
          condition: |
            sha == 'week4demo:<tag>'
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1710645807319
        repoName: carthmannH/week4
        build: <+input>
  identifier: BuildPushSTOScanRepoScanContainer
  tags: {}
  name: BuildPushPytestSTOScanRepo
