apiVersion: v1
kind: Service
metadata:
  name: week4demo
  labels:
    app: week4demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: week4demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: week4demo
  labels:
    app: week4demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week4demo
  template:
    metadata:
      labels:
        app: week4demo
    spec:
      containers:
      - name: week4demo
        image: week4demo:32
        ports:
        - containerPort: 8080
