apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigilant_williams
spec:
  selector:
    matchLabels:
      app: Nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: vigilant_williams
        image: week4demo:32
        ports:
        - containerPort: 8080
