apiVersion: apps/v1
kind: Deployment
metadata:
  name: week4demo
spec:
  selector:
    matchLabels:
      app: week4demo
  replicas: 3
  template:
    metadata:
      labels:
        app: week4demo
    spec:
      containers:
      - name: week4demo
        image: week4demo:32
        ports:
        - containerPort: 8080
