apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigilant_williams
spec:
  selector:
    matchLabels:
      app: Nodejs
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
