name: myapp
replicas: 2

image: <+artifact.image>
# dockercfg: <+artifact.imagePullSecret>

createNamespace: True
namespace: <+infra.namespace>

service:
  type: LoadBalancer
  ports:
    port: 8080  # Service port
    targetPort: 4949  # Target port

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.
#env:
 # config:
 #  key1: value10
 # secrets:
 #   key2: value2
