pipeline:
  name: Build week4
  identifier: Build_carthmannH_week4_1710645829913
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |+
                      sha=$(git rev-parse HEAD)

                    outputVariables:
                      - name: sha
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
    - stage:
        name: "Build and push "
        identifier: Build_and_push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: demo
                    repo: carthmannh/week4demo
                    tags:
                      - <+pipeline.variables.sha_tag>
                    dockerfile: Dockerfile
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1710645807319
        repoName: carthmannH/week4
        build: <+input>
  variables:
    - name: sha_tag
      type: String
      description: ""
      required: false
      value: sha
