pipeline:
  name: Build week4
  identifier: Build_carthmannH_week4_1710645829913
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: "Extract Sha "
        identifier: Extract_Sha
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          sha=$(git rev-parse HEAD)
                          export sha
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: echo $sha
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1710645807319
        repoName: carthmannH/week4
        build: <+input>
