pipeline:
  name: Build week4
  identifier: Build_carthmannH_week4_1710645829913
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      sha=$(git rev-parse HEAD)
                      echo $sha
                      export $sha
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1710645807319
        repoName: carthmannH/week4
        build: <+input>
