apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: 
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: demopod
        image:  {{.Values.image}}
        ports:
        - containerPort: 80
