apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-blue
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        color: blue
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}:blue
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-green
  namespace: demo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        color: green
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}:green
        ports:
        - containerPort: 8080

