apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo-ns  # Specify the namespace for myapp deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: <+artifact.image>
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: demo-prod  # Specify the namespace for myapp-green deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: <+artifact.image>
        ports:
        - containerPort: 8080
