apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  annotations:
    harness.io/direct-apply: "true" # Marking as non-primary
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}  # Add labels for identifying the application
    spec:
      initContainers:
      - name: port-forward
        image: appropriate/curl # Use an image with tools needed for port forwarding
        command: ['sh', '-c', 'kubectl port-forward svc/{{.Values.name}}-service 8080:8080 &']
      containers:
      - name: demopod
        image: {{.Values.image}}
        ports:
        - containerPort: 80 # Port in the container to listen on
          name: http
        - containerPort: 8080 # Port in the container to forward
