apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}  # Add labels for identifying the application
    spec:
      containers:
      - name: demopod
        image: {{.Values.image}}
        ports:
        - containerPort: 80 # Port in the container
        # Define port forwarding
        ports:
        - containerPort: 8080 # Port in the container to forward
