apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: demo-ns
spec:
  selector:
    app: myapp
 service:
  type: LoadBalancer
  ports:
    port: 8080  # Service port
    targetPort: 4949  # Target port
