apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  annotations:
    harness.io/primary-service: "true"  # Marking as primary service
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: myapp  # Replace with your app label selector

