apiVersion: v1
kind: Service
metadata:
  name:{{.Values.name}}
spec:
  type:{{.Values.serviceType}}
  ports:
  - port:
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: demopod  
