apiVersion: v1
kind: Service
metadata:
  name: myapp-svc  # Replace with your service name
spec:
  type: LoadBalancer  # Replace with your service type (e.g., NodePort, ClusterIP)
  loadBalancerIP: 127.0.0.1
  ports:
  - port: 80  # Replace with your service port
    targetPort: 8080  # Replace with your service target port
    protocol: TCP
  selector:
    app: myapp  # Replace with your app label selector
