apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: demo-ns
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 8080  # Service port
      targetPort: 4949  # Target port - Port on which your application listens inside the pod
