apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
    harness.io/color: blue

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-stage
spec:
  selector:
    app: myapp
