apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  annotations:
    harness.io/primary-service: "true"  # Marking as primary service
spec:
  selector:
    app: myapp
    harness.io/color: blue

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-stage
  annotations:
    harness.io/stage-service: "true"  # Marking as stage service
spec:
  selector:
    app: myapp
