apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: demo-ns
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 4949  # Updated service port to match the target port
      targetPort: 4949  # Target port - Port on which your application listens inside the pod
